# SPDX-License-Identifier: 0BSD
# Author: Makkhawan Sardlah

name: CI
on:
    release: 
        types: [published]

permissions:
  contents: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  BUILD:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Make
        run: sudo apt update && sudo apt install -y make
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.1'
          cache-dependency-path: go.work
      - uses: actions/checkout@v4
      - name: Test compile
        run: make build_test
      - name: Test Use
        timeout-minutes: 3
        run: tests/pull_license.bash
